In [ ]:
def f(x):
    return x>5 and x<10

mylist=[8,3,2,10,15,7,1,9,0,11]
list(filter(f,mylist))

In [ ]:
mylist=[8,3,2,10,15,7,1,9,0,11]
list(filter(lambda x: x >5 and x < 10 , mylist))

# 재귀(recursive call) p.269

In [ ]:
def count(num):
    if num>=1:
        print(num, end=' ')
        count(num-1)
    else:
        return
N=int(input('카운트 할 숫자 : '))
count(N)

In [ ]:
inStr='''
코스모스는 과거에 있었고, 현재에 있으며, 미래에 있을 그 모든 것이다.
우리는 코스모스의 일부다
이것은 결코 시적 수사가 아니다.
'''
def letterCount():
    global inStr
    countDic={}
    countList=[]
    
    #
    
    #
    
    return countList

# 모듈 & 패키지 p.272

In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()
print(iris)

# 클래스 p.281

In [ ]:
class CAR:
    color =''
    name=''
    speed=0
    
    def __init__(self):
        self.color='white'
        self.speed = 0
    
    def u_speed(self,val):
        self.speed+=val
    
    def d_speed(self,val):
        self.speed-=val
        


In [ ]:
mycar1=CAR()
mycar2=CAR()
mycar3=CAR()
mycar4=CAR()

mycar1.color='black'
mycar1.speed=0

mycar2.color='red'
mycar2.speed=0
mycar3.color='blue'
mycar3.speed=0

print(f'색상은 : {mycar1.color} 속도는 : {mycar1.speed}')
print(f'색상은 : {mycar2.color} 속도는 : {mycar2.speed}')
print(f'색상은 : {mycar3.color} 속도는 : {mycar3.speed}')
print(f'색상은 : {mycar4.color} 속도는 : {mycar4.speed}')

In [1]:
class CAR:
    color =''
    name=''
    speed=0
    
    def __init__(self,val1,val2,val3):
        self.color=val1
        self.name=val2
        self.speed = val3

    def getcolor(self):
        return self.color
    def getname(self):
        return self.name
    def getspeed(self):
        return self.speed

class Truck(CAR):
    load_value=0
    def getloadvalue

In [7]:
car1,car2=None,None

car1=CAR('흰색','아우디',0)
car2=CAR('검정색','벤츠',30)

print('%s %s의 현재 속도는 %d 입니다.'%(car1.getcolor(),car1.getname(),car1.getspeed()))
print(f'{car2.getcolor()} {car2.getname()}의 현재 속도는 {car2.getspeed()}입니다.')

흰색 아우디의 현재 속도는 0 입니다.
검정색 벤츠의 현재 속도는 30입니다.


In [18]:
class Car:

    def upspeed(self,value):
        self.speed+=value
        
        print(f'현재 속도(슈퍼 클래스 {self.speed})')
        
class Sedan(Car) :
    def upspeed(self, value):
        self.speed+=value
        
        if self.speed>150:
            self.speed = 150
        print(f'현재 속도(서브 클래스 {self.speed})')
class Sonata(Sedan):
    pass

In [17]:
sedan1,truck1,sonata1=None,None,None

truck1=Car()
sedan1=Sedan()
sonata1=Sonata()
print('트럭 ---> ',end='')
truck1.upspeed(200)
print('세단 --> ',end='')
sedan1.upspeed(200)
print('소나타 -->',end='')
sonata1.upspeed(200)


트럭 ---> 현재 속도(슈퍼 클래스 200)
세단 --> 현재 속도(서브 클래스 150)
소나타 -->현재 속도(서브 클래스 150)


# 장바구니 문제 p.304

In [119]:
class Basket:

    def __init__(self,id):
        self.id=id
        self.item=[]
        self.price=[]
        self.qty=[]
        self.totalprice=0
        self.totalcount=0
    def add(self,item,price,qty):
        self.item.append(item)
        self.price.append(price)
        self.qty.append(qty)
        self.totalprice+=price*qty
        self.totalcount+=1
    def delete(self,item,qty):
        for i in range(self.totalcount):
            if item==self.item[i]:
                self.totalprice -= self.price[i]*qty
                self.qty[i]-=qty
                
    def printitems(self):
        print(f'#{self.id}의 장바구니')
        print('-'*20)
        for i, v in enumerate(self.item):
            print(f'{v} {self.price[i]} {self.qty[i]}')
        print(f'** 전체가격 ={self.totalprice}, 전체종류수= {self.totalcount}')
        print('-'*20)

In [120]:
bask1= Basket('지애')
bask2= Basket('지현')

bask1.add('바나나',3000,2)
bask1.add('우유',2500,2)
bask1.add('라면',4000,1)
bask2.add('라면',4000,2)
bask1.delete('우유',1)


bask1.printitems()
bask2.printitems()

#지애의 장바구니
--------------------
바나나 3000 2
우유 2500 1
라면 4000 1
** 전체가격 =12500, 전체종류수= 3
--------------------
#지현의 장바구니
--------------------
라면 4000 2
** 전체가격 =8000, 전체종류수= 1
--------------------


In [121]:
class Basket:
    def __init__(self, id):
        self.id = id
        self.바구니={}
    def add(self, item, price, qty):
        self.바구니[item]=[price,qty]
    def delete(self, item, qty):
        self.바구니[item][1] -= qty
    def printitems(self):
        print(f'# {self.id}의 장바구니')
        print('-'*30)
        total = 0
        cnt = len(self.바구니)
        for key in self.바구니:
            print(f'* {key:10} {self.바구니[key][0]} {self.바구니[key][1]}')
            total += self.바구니[key][0] * self.바구니[key][1]
        print(f'** 전체가격 =  {total} 전체 수량 = {cnt}')

In [122]:
basket1 = Basket("제인")
basket2 = Basket("대원")
basket1.add('바나나',3000,2)
basket1.add('우유',2500,2)
basket1.add('라면',4000,1)
basket2.add('라면',4000, 2)
basket1.delete('우유',1)
basket1.printitems()
basket2.printitems()

# 제인의 장바구니
------------------------------
* 바나나        3000 2
* 우유         2500 1
* 라면         4000 1
** 전체가격 =  12500 전체 수량 = 3
# 대원의 장바구니
------------------------------
* 라면         4000 2
** 전체가격 =  8000 전체 수량 = 1


# p.307까지 진행되었고 NUMPY로 전환됨

In [127]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [143]:
import numpy as np
arr=np.array([[10,20,30,40],
              [50,60,70,80]])
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(len(arr))
print(arr[1])
print(arr1*10)

[[10 20 30 40]
 [50 60 70 80]]
2
[50 60 70 80]
[[10 20 30 40]
 [50 60 70 80]]


In [145]:
arr1=np.array([1,2,3])
print(arr1.ndim)
print(arr1.shape)
arr2=np.array([[0,1,2],[3,4,5]])
print(arr2.ndim)
print(arr2.shape)

1
(3,)
2
(2, 3)


In [149]:
na=np.arange(12)
nb=na.reshape(3,4)
print(nb)
print('')
nb=na.reshape(3,-1)#위에랑 같지만 이거는 3행으로 하되 자동으로
print(nb)
print('')
nb=na.reshape(2,2,-1)#이거는 2행 2열 N축을 자동으로=3차원 행렬임
print(nb)
print('')
nc = nb.flatten()#이건 다차원을 무조건 1차원으로 변환
print(nc)
print('')
nc = nb.ravel()#이것두
print(nc)
print('')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[ 0  1  2  3  4  5  6  7  8  9 10 11]



In [150]:
arr=np.array([0,1,2,3,4])

print(arr[2])#두번째
print(arr[1:3])#2~3번째
print(arr[::-1])#역순으로 배열

2
[1 2]
[4 3 2 1 0]


In [155]:
print(np.iinfo('int64'))
print(np.finfo('float64'))

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
---------------------------------------------------------------



In [157]:
na=np.array([0,1,2,3,4])
print(na)
print(na.dtype)

na=na.astype(np.float64)
print(na)
print(na.dtype)

[0 1 2 3 4]
int32
[0. 1. 2. 3. 4.]
float64


In [164]:
na=np.zeros(5)#float타입으로 안의 숫자를 0으로 채운 1차원 배열을 생성
print(na)
print('')
na=np.zeros((2,5))#물론 다차원선언도 가능
print(na)
print('')
na=np.empty((3,1))#빈공간에 저 크기만큼의 행렬을 선선 값은 쓰레기값
print(na)
print('')

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [176]:
na1=np.ones((3,2))
na2=np.zeros((3,3))
na3=np.array([[10,20,30,40,50],[60,70,80,90,100],[110,120,130,140,150]])
na4=np.hstack([na2,na1])
na5=np.vstack([na4,na3])
na6=np.vstack([na5,na5])
print(na6)

[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


In [179]:
arr1= np.array([[1,2],[4,5]])
arr2=np.array([[11,12],[13,14]])
print(arr2*arr1)

[[11 24]
 [52 70]]


# numpy p.40까지